package pw.tmg.client.module.mac;

import org.bridj.BridJ;
import org.bridj.CRuntime;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.ann.Library;
import org.bridj.ann.Runtime;
/**
 * Wrapper for library <b>mac-utils</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mac-utils")
@Runtime(CRuntime.class)
public class MacBridge {
    static {
        BridJ.register();
    }
    public static abstract class notification_callback extends Callback<notification_callback > {
        public abstract void apply();
    };
    /**
     * Original signature : <code>int sendNotification(const char*, const char*, const char*, const char*, notification_callback)</code><br>
     * <i>native declaration : line 16</i>
     */
    public static native int sendNotification(Pointer<Byte > title, Pointer<Byte > subtitle, Pointer<Byte > message, Pointer<Byte > sound, Pointer<MacBridge.notification_callback > callback);
    /**
     * Original signature : <code>PasteboardContent** getPasteboardContents()</code><br>
     * <i>native declaration : line 17</i>
     */
    public static native Pointer<Pointer<PasteboardContent > > getPasteboardContents();
    /**
     * Original signature : <code>int writeToPasteboard(const char*)</code><br>
     * <i>native declaration : line 18</i>
     */
    public static native int writeToPasteboard(Pointer<Byte > data);
}

