package pw.tmg.client.module.mac;

import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("mac-utils")
public class PasteboardContent extends StructObject {
    static {
        BridJ.register();
    }
    /** C type : const char* */
    @Field(0)
    public Pointer<Byte > type() {
        return this.io.getPointerField(this, 0);
    }
    /** C type : const char* */
    @Field(0)
    public PasteboardContent type(Pointer<Byte > type) {
        this.io.setPointerField(this, 0, type);
        return this;
    }
    /** C type : unsigned char* */
    @Field(1)
    public Pointer<Byte > data() {
        return this.io.getPointerField(this, 1);
    }
    /** C type : unsigned char* */
    @Field(1)
    public PasteboardContent data(Pointer<Byte > data) {
        this.io.setPointerField(this, 1, data);
        return this;
    }
    @CLong
    @Field(2)
    public long length() {
        return this.io.getCLongField(this, 2);
    }
    @CLong
    @Field(2)
    public PasteboardContent length(long length) {
        this.io.setCLongField(this, 2, length);
        return this;
    }
    public PasteboardContent() {
        super();
    }
    public PasteboardContent(Pointer pointer) {
        super(pointer);
    }
}
